name: Setup Node

description: run setup-node

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn

