name: Install & Cache Dependencies

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Load Cache
      uses: ./.github/actions/load-yarn-cache

    - name: Install
      run: yarn --frozen-lockfile
