name: Setup Node & Install Dependencies

description: Setup Node & Install Dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn

    - name: Install
      run: yarn --frozen-lockfile
      shell: bash
