name: Tests

on: workflow_call

jobs:
  install:
    # runs install first so that other jobs can install dependencies from cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

  e2e-tests:
    runs-on: ubuntu-latest
    needs: install
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Unit Tests
        run: yarn test:e2e

      - name: Save report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run Unit Tests
        run: yarn test:unit




