name: Tests

on:
  push:
    branches: [master, vercel-release, actions]


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Run Unit Tests
        run: yarn test:unit




